### PR TITLE
BTDB IOC Benchmark

### PR DESCRIPTION
**Pull request by Bobris**

### CODE REVIEW

**Comment by Bobris** [comment]
BTDB supports Keyed registrations, and could dynamically add "derived" registrations, that's why is little bit slower than LightInject or SimpleInject.

**Comment by dotnetjunkie** [comment]
I could add keyed registrations to Simple Injector without affecting performance of non-keyed resolves, so I'm not sure that's a valid argument.

**Comment by Bobris** [comment]
@dotnetjunkie Not meant to bash your very nice IOC implementation. We both know that this mostly benchmark chosen speed of lookup tables, because I am sure all IL generating code implementations generates same or similar IL code. In BTDB IOC if you really want to have speed you can resolve Func<ITransient> and then you have identical speed to "Direct" (this is what I meant by "derived" registrations).

**Comment by dotnetjunkie** [comment]
@Bobris I didn't interpret your comment at a bash at all. Just wanted to explain that I think that adding features like named/keyed registration shouldn't have to influence performance of non-keyed registrations. If it does influence this, it's because of design and implementation trade-offs.

**Pull request merged**
